spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tasksdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: qM8f5GQ+z9Kc2Daf4mXhz1FBQn2lOj8MeXzKpU3SxGA=
  expiration: 3600000  # 1 hora

api:
  path: /api/tasks